version: "3.7"

services:
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: phpmyadmin
    networks:
      - mysql
    ports:
      - 8080:80
    environment:
      PMA_ARBITRARY: 1

  mysql:
    image: mysql:8.0
    container_name: mysql
    networks:
      - mysql
    ports:
      - 3306:3306
    environment:
      MYSQL_ROOT_PASSWORD: 1234
    volumes:
      - mysql:/var/lib/mysql
      - ./mysql-init:/docker-entrypoint-initdb.d

networks:
  mysql:


volumes:
  mysql:
